// Scenario: notification fan-out under sustained alert volume (Phase 15 load-testing expansion).
//
// Each iteration fires a distinct, high-severity alert designed to match a routing rule that
// fans out to multiple channels (email via Mailpit + webhook via webhook-sink + in-app — see
// docs/development/alert-ingestion.md's routing section and infrastructure/docker/observability
// config for the exact rule). k6 measures only alert-acceptance latency; actual notification
// delivery/dead-letter counts are asynchronous and are sampled separately by
// infrastructure/docker/scripts/benchmark-run.sh from incident-service's
// /actuator/prometheus notification metrics before/during/after the run — the same
// acceptance-vs-completion separation used by incident-creation.js.
//
// Configurable via env vars: BENCHMARK_RATE (default 10, requests/sec), BENCHMARK_DURATION
// (default 1m), ALERTS_ALERTMANAGER_SHARED_TOKEN (required).
import http from "k6/http";
import { check } from "k6";
import { Trend } from "k6/metrics";
import { BASE_URL, RUN_ID } from "../lib/common.js";

const RATE = parseInt(__ENV.BENCHMARK_RATE || "10", 10);
const DURATION = __ENV.BENCHMARK_DURATION || "1m";
const TOKEN = __ENV.ALERTS_ALERTMANAGER_SHARED_TOKEN;

export const ingestLatency = new Trend("notification_fanout_ingest_duration", true);

export const options = {
  scenarios: {
    notification_fanout: {
      executor: "constant-arrival-rate",
      rate: RATE,
      timeUnit: "1s",
      duration: DURATION,
      preAllocatedVUs: Math.max(10, Math.ceil(RATE / 2)),
      maxVUs: RATE * 2,
    },
  },
  thresholds: {
    http_req_failed: ["rate<0.02"],
  },
};

export default function () {
  if (!TOKEN) {
    throw new Error("ALERTS_ALERTMANAGER_SHARED_TOKEN is required for this scenario");
  }
  const fingerprint = `fanout-${RUN_ID}-${__VU}-${__ITER}-${Date.now()}`;
  const startsAt = new Date().toISOString();
  const payload = JSON.stringify({
    version: "4",
    status: "firing",
    receiver: "sentinelops-incident-service",
    alerts: [
      {
        status: "firing",
        labels: {
          alertname: "NotificationFanoutLoadTest",
          severity: "critical",
          service: "k6-load-test",
          environment: "production",
          instance: fingerprint,
        },
        annotations: {
          summary: "Synthetic notification-fanout load-test alert",
          description: "Generated by notification-fanout.js",
        },
        startsAt,
        endsAt: "0001-01-01T00:00:00Z",
        generatorURL: "http://prometheus:9090/graph",
        fingerprint,
      },
    ],
  });

  const res = http.post(`${BASE_URL}/api/v1/alerts/webhooks/alertmanager`, payload, {
    headers: {
      Authorization: `Bearer ${TOKEN}`,
      "Content-Type": "application/json",
    },
    tags: { name: "ingest-alert-for-fanout" },
  });

  ingestLatency.add(res.timings.duration);
  check(res, { "alert accepted": (r) => r.status === 202 });
}
