package com.sentinelops.incident.ai.provider;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.sentinelops.incident.ai.TriageSuggestion;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * A deterministic, rule-based, network-free provider — used by default in tests and CI (see {@code
 * sentinelops.ai.provider=deterministic}), and as a safe local fallback with no model download
 * required. It never invents a citation: every citation it emits is copied directly from the
 * passages it was actually given, never fabricated. Its severity suggestion always exactly mirrors
 * the incident's own current severity (the only value it can respond with any real confidence
 * about), never a fabricated escalation/de-escalation guess.
 */
public class DeterministicAiProvider implements AiProvider {

  private static final Map<String, String> CATEGORY_KEYWORDS =
      Map.ofEntries(
          Map.entry("latency", "Performance"),
          Map.entry("slow", "Performance"),
          Map.entry("timeout", "Performance"),
          Map.entry("connection pool", "Database"),
          Map.entry("database", "Database"),
          Map.entry("postgres", "Database"),
          Map.entry("consumer lag", "Messaging"),
          Map.entry("kafka", "Messaging"),
          Map.entry("redpanda", "Messaging"),
          Map.entry("dead letter", "Event Delivery"),
          Map.entry("dead-letter", "Event Delivery"),
          Map.entry("outbox", "Event Delivery"),
          Map.entry("auth", "Authentication"),
          Map.entry("401", "Authentication"),
          Map.entry("403", "Authentication"),
          Map.entry("token", "Authentication"),
          Map.entry("deploy", "Deployment"),
          Map.entry("rollout", "Deployment"),
          Map.entry("regression", "Deployment"),
          Map.entry("health check", "Availability"),
          Map.entry("readiness", "Availability"),
          Map.entry("liveness", "Availability"));

  private final ObjectMapper objectMapper;

  public DeterministicAiProvider(ObjectMapper objectMapper) {
    this.objectMapper = objectMapper;
  }

  @Override
  public ProviderResult generate(TriageContext context) {
    String haystack =
        (nullToEmpty(context.incidentTitle()) + " " + nullToEmpty(context.incidentDescription()))
            .toLowerCase(Locale.ROOT);
    String category = "Uncategorized";
    for (var entry : CATEGORY_KEYWORDS.entrySet()) {
      if (haystack.contains(entry.getKey())) {
        category = entry.getValue();
        break;
      }
    }

    List<String> evidence = new ArrayList<>();
    evidence.add(
        "Reported severity: " + context.severity() + "; current status: " + context.status());
    evidence.add(
        "Affected service: " + context.affectedService() + " (source: " + context.source() + ")");
    for (String entry : context.timelineSummaries().stream().limit(3).toList()) {
      evidence.add("Timeline: " + entry);
    }

    List<TriageSuggestion.Citation> citations =
        context.passages().stream()
            .map(
                p ->
                    new TriageSuggestion.Citation(
                        p.chunkId(), p.sourceTitle(), p.section(), p.score()))
            .toList();

    List<String> diagnosticSteps =
        context.passages().isEmpty()
            ? List.of(
                "No runbook passage matched this incident closely enough to suggest specific"
                    + " steps — begin with the standard investigation checklist for "
                    + context.affectedService()
                    + ".")
            : List.of(
                "Review the retrieved runbook passage(s) below for this incident's specific"
                    + " diagnostic steps.",
                "Confirm the symptom described in the incident matches the runbook's documented"
                    + " symptoms before following its steps.");

    List<String> escalationConditions =
        List.of(
            "Escalate per the retrieved runbook's own escalation conditions, if any passage was"
                + " retrieved.",
            "Escalate immediately regardless of this suggestion if customer impact is confirmed"
                + " and worsening.");

    TriageSuggestion suggestion =
        new TriageSuggestion(
            "Deterministic summary: a "
                + context.severity()
                + " incident affecting "
                + context.affectedService()
                + ", currently "
                + context.status()
                + ". This summary is rule-based (no language model was used).",
            category,
            context.severity(),
            "Low confidence — generated by the deterministic fallback provider, not a language"
                + " model. Treat as a starting point only.",
            evidence,
            diagnosticSteps,
            escalationConditions,
            citations,
            List.of(
                "This suggestion was produced by a deterministic, rule-based provider, not an"
                    + " LLM — category and steps are keyword-derived and may be wrong.",
                "All suggestions require human review before any action is taken."));

    try {
      return new ProviderResult.Success(objectMapper.writeValueAsString(suggestion));
    } catch (Exception e) {
      return new ProviderResult.Failure(
          "Could not serialize deterministic suggestion: " + e.getMessage());
    }
  }

  @Override
  public String name() {
    return "deterministic-rules-v1";
  }

  private String nullToEmpty(String value) {
    return value == null ? "" : value;
  }
}
